version: '3.8'

services:
  app:
    volumes:
      - .:/usr/src/app          # Monta o código local
      - /usr/src/app/node_modules # Evita sobrescrever node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"  # Para o hot reload (necessário em Windows e WSL)
      CHOKIDAR_INTERVAL: 500
